<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Cetak Daftar_input_cari</name>
   <tag></tag>
   <elementGuidId>a27635c3-8348-4574-9d86-153df22243fb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;input_cari&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='input_cari']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>64d3dd2d-3fb6-4422-9e9b-86d3911f741a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>8019bb0b-624b-45d4-b720-58e0d33f9e9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>input_cari</value>
      <webElementGuid>65513e79-a06b-4bf7-8eea-1102ac201634</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukkan Kata Kunci</value>
      <webElementGuid>5b90794e-6354-4f98-82b6-cd4df4545219</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wrapper&quot;)/div[@class=&quot;section&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-11&quot;]/div[1]/form[1]/input[1]</value>
      <webElementGuid>565829dd-a749-4199-b1cc-dfc06536765d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='input_cari']</value>
      <webElementGuid>4aeb788f-556f-431e-ab27-6b3d71d05881</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wrapper']/div[2]/div/div/div/div/form/input</value>
      <webElementGuid>ba1b3a39-efe0-4c3a-8a72-c2bf810e513f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>3508268a-65ba-4e05-b785-9bec5822c40a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'input_cari' and @placeholder = 'Masukkan Kata Kunci']</value>
      <webElementGuid>363b8ac0-ee55-4529-9e45-a6451ed4e03b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
