<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Id User_id_user (1)</name>
   <tag></tag>
   <elementGuidId>01bd34b0-3ac1-4355-b8a2-8eb92568c401</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#id_user</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='id_user']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5d5658a8-51f5-48d4-aea7-542206705f63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>bd8d33e9-7463-404f-9c36-f772d6adbdc1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>id_user</value>
      <webElementGuid>20f43a86-f490-4044-80c8-69bbc53b6c4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>id_user</value>
      <webElementGuid>6f328e1f-1060-4945-a3fd-f5410fbdb77b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>66a8bde0-af45-47aa-9504-868e9df5a23d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Id User</value>
      <webElementGuid>41a01375-d12d-4f87-b5ab-ad81c92d5f3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>230e10aa-903b-43af-92e6-ac1fdc68feb3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;id_user&quot;)</value>
      <webElementGuid>88b9214e-ba30-476a-9d0a-0adebfc2ed9d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='id_user']</value>
      <webElementGuid>13d27d1c-a36c-4232-bff5-e44ec8133412</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='demoForm']/div/input</value>
      <webElementGuid>0517a850-a45d-449e-b416-1d9c55630d89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>446809d5-e158-4552-b587-85cc8d69726e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'id_user' and @id = 'id_user' and @type = 'text' and @placeholder = 'Id User']</value>
      <webElementGuid>2788ecee-539f-4c68-a81b-6c584339ed33</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
