<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_KecamatanMUARA ANCALONGBUSANGLONG ME_c9d7ea</name>
   <tag></tag>
   <elementGuidId>adda5efe-3cfa-4fa6-8b38-dd882dc1c40a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Kec</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='Kec']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>12e66735-1213-4dec-9964-ac4b0310a882</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>7d551f10-44a6-4f0c-88ff-66b3e1073d95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Kec</value>
      <webElementGuid>53d03762-4e12-4f2e-8975-b99eae5ab596</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Kecamatan</value>
      <webElementGuid>cb705a31-df04-4a2e-b22f-453187e750a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>KecamatanMUARA ANCALONGBUSANGLONG MESANGATMUARA WAHAUTELENKONGBENGMUARA BENGKALBATU AMPARSANGATTA UTARABENGALONTELUK PANDANSANGATTA SELATANRANTAU PULUNGSANGKULIRANGKALIORANGSANDARANKAUBUNKARANGAN</value>
      <webElementGuid>768977f9-d637-4494-b0ac-44e567c1f4de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Kec&quot;)</value>
      <webElementGuid>698f2272-e3c1-4fcb-95e7-654e479c35d0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='Kec']</value>
      <webElementGuid>1e9e733c-0554-4e1d-957b-81ec3402a225</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='demoForm']/div[7]/div/div[2]/select</value>
      <webElementGuid>47076341-5a12-4ea8-b646-d0ea3fbbf99e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kecamatan *'])[1]/following::select[1]</value>
      <webElementGuid>b586e924-05f2-4090-807e-799766e55131</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kabupaten *'])[1]/following::select[2]</value>
      <webElementGuid>5398c748-3547-4fae-9fbc-e9d2cfb6c0af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Desa / Kelurahan *'])[1]/preceding::select[1]</value>
      <webElementGuid>4b955176-a7d1-4e6d-9b95-cca41b2bcd23</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nomor Telepon *'])[1]/preceding::select[2]</value>
      <webElementGuid>32d5d9f8-7188-4f7d-b919-05bd611eead2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/select</value>
      <webElementGuid>79a5f4f2-899c-4f31-bf8f-d5d7dbb9dc72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'Kec' and @name = 'Kecamatan' and (text() = 'KecamatanMUARA ANCALONGBUSANGLONG MESANGATMUARA WAHAUTELENKONGBENGMUARA BENGKALBATU AMPARSANGATTA UTARABENGALONTELUK PANDANSANGATTA SELATANRANTAU PULUNGSANGKULIRANGKALIORANGSANDARANKAUBUNKARANGAN' or . = 'KecamatanMUARA ANCALONGBUSANGLONG MESANGATMUARA WAHAUTELENKONGBENGMUARA BENGKALBATU AMPARSANGATTA UTARABENGALONTELUK PANDANSANGATTA SELATANRANTAU PULUNGSANGKULIRANGKALIORANGSANDARANKAUBUNKARANGAN')]</value>
      <webElementGuid>4664d7c0-e5a3-4af5-8a52-c20c563d86f8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
