<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Islam                               _f363b0</name>
   <tag></tag>
   <elementGuidId>4bceeae1-f224-4776-98fd-2baae981e6ae</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>select[name=&quot;agama&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@name='agama']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>954babc5-3b14-4091-b173-e6f41dcc436e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>d2398c4d-c48e-4832-a55a-f449100dde54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>agama</value>
      <webElementGuid>bcc84f5e-be32-469f-9947-5a48c4fa7451</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                    Islam
                                    Hindu
                                    Katolik
                                    Kristen
                                    Budha
                                    Konghucu
                                </value>
      <webElementGuid>d7e127c2-4164-48e9-b97c-bc804c5d416a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;demoForm&quot;)/div[@class=&quot;form-group&quot;]/div[@class=&quot;form-group&quot;]/select[@class=&quot;form-control&quot;]</value>
      <webElementGuid>dde1a440-e759-47a5-b756-fb64d7d34287</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@name='agama']</value>
      <webElementGuid>d3ec5260-f5ea-4e63-b7a4-cfbcf76814aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='demoForm']/div[7]/div[8]/select</value>
      <webElementGuid>293cd560-56af-4634-8aba-9348a04316f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Agama *'])[1]/following::select[1]</value>
      <webElementGuid>e7a871e4-eaae-467a-8bd0-a4f5580f4b02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Email *'])[1]/following::select[1]</value>
      <webElementGuid>ad63db54-d632-46cb-9122-8d4ad1358863</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Deskripsi Keahlian *'])[1]/preceding::select[1]</value>
      <webElementGuid>fb1239e4-d4c0-487b-9654-5d1fe15f8789</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Status Petani *'])[1]/preceding::select[1]</value>
      <webElementGuid>9fa69dcd-ffd6-4493-8fa1-59d78b2dc1a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/select</value>
      <webElementGuid>ef79e856-85a8-4a07-9276-47009f25f265</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'agama' and (text() = '
                                    Islam
                                    Hindu
                                    Katolik
                                    Kristen
                                    Budha
                                    Konghucu
                                ' or . = '
                                    Islam
                                    Hindu
                                    Katolik
                                    Kristen
                                    Budha
                                    Konghucu
                                ')]</value>
      <webElementGuid>01ed1669-ca27-4b91-b25d-218697dde989</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
