<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_KabupatenKABUPATEN BERAUKABUPATEN KU_ad2e2e</name>
   <tag></tag>
   <elementGuidId>61386b23-de9b-40fb-b750-0d37bc11c613</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Kab</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='Kab']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>52c2a7ab-fe3d-4fa3-82a5-914836a0d2a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>3a525200-076f-4893-a612-fe15c5d7a671</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Kab</value>
      <webElementGuid>c773829c-8a33-4caa-b06c-33dcb8706d0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Kabupaten</value>
      <webElementGuid>a0526224-59e0-4a6f-bd1f-7a9ad1c3dfa3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>KabupatenKABUPATEN BERAUKABUPATEN KUTAI BARATKABUPATEN KUTAI KARTANEGARAKABUPATEN KUTAI TIMURKABUPATEN MAHAKAM HULUKABUPATEN PASERKABUPATEN PENAJAM PASER UTARAKOTA BALIKPAPANKOTA BONTANGKOTA SAMARINDA</value>
      <webElementGuid>a1117a70-74a5-4ed9-ae4c-28e35279c4b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Kab&quot;)</value>
      <webElementGuid>c9de8cad-034e-4c31-bb6d-c04c263c091e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='Kab']</value>
      <webElementGuid>410c301b-fa55-487c-a5b4-dececb7751e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='demoForm']/div[7]/div/div/select</value>
      <webElementGuid>0a755a1d-38b5-4e26-b617-c40ef8801e73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kabupaten *'])[1]/following::select[1]</value>
      <webElementGuid>ec9da5cb-574e-4bfe-85e6-90363db48737</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Provinsi *'])[1]/following::select[2]</value>
      <webElementGuid>5e715cf2-476c-49a3-964b-2d4f38ec2bee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kecamatan *'])[1]/preceding::select[1]</value>
      <webElementGuid>532509dd-c00e-4dd4-8c4e-50e132416e90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Desa / Kelurahan *'])[1]/preceding::select[2]</value>
      <webElementGuid>3c0c6cd4-77b5-406b-a668-1cf1e66fc429</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/div/select</value>
      <webElementGuid>4aadbbe6-a4b7-4453-95b2-e36459b8f093</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'Kab' and @name = 'Kabupaten' and (text() = 'KabupatenKABUPATEN BERAUKABUPATEN KUTAI BARATKABUPATEN KUTAI KARTANEGARAKABUPATEN KUTAI TIMURKABUPATEN MAHAKAM HULUKABUPATEN PASERKABUPATEN PENAJAM PASER UTARAKOTA BALIKPAPANKOTA BONTANGKOTA SAMARINDA' or . = 'KabupatenKABUPATEN BERAUKABUPATEN KUTAI BARATKABUPATEN KUTAI KARTANEGARAKABUPATEN KUTAI TIMURKABUPATEN MAHAKAM HULUKABUPATEN PASERKABUPATEN PENAJAM PASER UTARAKOTA BALIKPAPANKOTA BONTANGKOTA SAMARINDA')]</value>
      <webElementGuid>0fc05d12-e811-4f7c-8197-529773bde18d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
