<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_SD                                  _d31312</name>
   <tag></tag>
   <elementGuidId>db080d80-5600-4408-ad26-0925b402dcd1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>select[name=&quot;pendidikan_terakhir&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@name='pendidikan_terakhir']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>f4de0fd0-8bf5-40c3-b640-34a63d6f5929</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>da9e3749-76c2-44fd-9ce1-b7bd969acf67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>pendidikan_terakhir</value>
      <webElementGuid>fce7712b-f50f-40f9-bc70-d8284380313a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                    SD
                                    SMP
                                    SMA
                                    D1
                                    D2
                                    D3
                                    S1
                                    S2
                                    S3
                                </value>
      <webElementGuid>c361ee29-4312-4ebc-959f-da8c5ea2a3c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;demoForm&quot;)/div[@class=&quot;form-group&quot;]/div[@class=&quot;form-group&quot;]/select[@class=&quot;form-control&quot;]</value>
      <webElementGuid>a2772030-cd46-4da8-a900-27d647c41414</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@name='pendidikan_terakhir']</value>
      <webElementGuid>b0273cd9-cad6-4da0-81d9-a774a0558da7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='demoForm']/div[7]/div[3]/select</value>
      <webElementGuid>4b6a1dbf-6101-42b9-97b6-d8f40cc0372c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pendidikan Terakhir'])[1]/following::select[1]</value>
      <webElementGuid>ff223ebc-8e7b-4af7-a251-3964cdf9b9f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nomor Telepon *'])[1]/following::select[1]</value>
      <webElementGuid>5b086f28-290e-4ea5-9b53-e926cadb84c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jumlah Lahan *'])[1]/preceding::select[1]</value>
      <webElementGuid>93e82189-a98d-4668-9f61-72712c7af51f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jumlah Tanggungan *'])[1]/preceding::select[1]</value>
      <webElementGuid>9eac1329-b4d4-4350-97b7-11adbe6408e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/select</value>
      <webElementGuid>57b03b2d-8a13-4c55-ad37-ea2e0a8570e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'pendidikan_terakhir' and (text() = '
                                    SD
                                    SMP
                                    SMA
                                    D1
                                    D2
                                    D3
                                    S1
                                    S2
                                    S3
                                ' or . = '
                                    SD
                                    SMP
                                    SMA
                                    D1
                                    D2
                                    D3
                                    S1
                                    S2
                                    S3
                                ')]</value>
      <webElementGuid>e1b2852c-4965-4559-8af6-a7c07c4ee9a8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
