<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_KabupatenKABUPATEN BANGKAKABUPATEN B_0a108f</name>
   <tag></tag>
   <elementGuidId>40b47099-9d64-455a-a275-d21f3595e9e4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Kab</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='Kab']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>492aae3f-126d-4d8e-b3e2-6b593671146c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>cf951cdd-379c-48f3-95cd-bae43aad168d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Kab</value>
      <webElementGuid>4b7d2305-c587-4124-9581-540e77612039</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Kabupaten</value>
      <webElementGuid>5bc6042f-af8c-4282-9296-e65bbbcc4ae5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>KabupatenKABUPATEN BANGKAKABUPATEN BANGKA BARATKABUPATEN BANGKA SELATANKABUPATEN BANGKA TENGAHKABUPATEN BELITUNGKABUPATEN BELITUNG TIMURKOTA PANGKAL PINANG</value>
      <webElementGuid>1c018952-bed7-459d-9044-45547e7bf9a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Kab&quot;)</value>
      <webElementGuid>9e2b991f-b011-4d4f-adb8-b1f46760e2b9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='Kab']</value>
      <webElementGuid>10cd0208-6932-4006-a7b7-cef199ea74a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='demoForm']/div[7]/div/div/select</value>
      <webElementGuid>ad55056f-921f-4b25-b6d8-fd153d37dc22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kabupaten *'])[1]/following::select[1]</value>
      <webElementGuid>7ef7f357-831b-4b2e-8402-067a737181d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Provinsi *'])[1]/following::select[2]</value>
      <webElementGuid>fcaada69-4fad-4d62-8b89-96b1f5111047</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kecamatan *'])[1]/preceding::select[1]</value>
      <webElementGuid>7ed4389f-460d-4887-b522-d8a7950c0914</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Desa / Kelurahan *'])[1]/preceding::select[2]</value>
      <webElementGuid>cefee84a-6212-4195-8860-0d705ef6004a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/div/select</value>
      <webElementGuid>233b360b-71d8-4200-aa34-ddb91dcc9f2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'Kab' and @name = 'Kabupaten' and (text() = 'KabupatenKABUPATEN BANGKAKABUPATEN BANGKA BARATKABUPATEN BANGKA SELATANKABUPATEN BANGKA TENGAHKABUPATEN BELITUNGKABUPATEN BELITUNG TIMURKOTA PANGKAL PINANG' or . = 'KabupatenKABUPATEN BANGKAKABUPATEN BANGKA BARATKABUPATEN BANGKA SELATANKABUPATEN BANGKA TENGAHKABUPATEN BELITUNGKABUPATEN BELITUNG TIMURKOTA PANGKAL PINANG')]</value>
      <webElementGuid>599a91e0-4da3-40e9-abe8-3116241b8c7b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
