<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Desa  KelurahanBIKANGGADUNGJERIJIKAP_85a92b</name>
   <tag></tag>
   <elementGuidId>7082e857-d844-442a-a9ad-8617af73e58a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Desa</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='Desa']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>51c129a7-6a42-4f73-81bc-bedca12e276a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>8df4e35c-4901-4f96-93a5-1156d76288b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Desa</value>
      <webElementGuid>2edab712-972a-42ef-ae3e-1d50dd0931d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Desa_Kelurahan</value>
      <webElementGuid>400ab25c-e35f-463f-8d28-65e212810822</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Desa / KelurahanBIKANGGADUNGJERIJIKAPOSANGKEPOHRIASRINDIKSERDANGTANJUNG KETAPANGTELADANTOBOALI</value>
      <webElementGuid>f935a98e-2bed-4f55-b0a7-2018aa2d6050</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Desa&quot;)</value>
      <webElementGuid>55fa5633-9884-4971-be07-7ddd9c9bbddf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='Desa']</value>
      <webElementGuid>d760a313-f5ca-43ee-916c-28160045b614</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='demoForm']/div[7]/div/div[3]/select</value>
      <webElementGuid>60d9b2a6-e6d6-46fa-ae63-1718105635d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Desa / Kelurahan *'])[1]/following::select[1]</value>
      <webElementGuid>90d5c4bf-1d0e-4dfb-8228-37a0ce2fd0b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kecamatan *'])[1]/following::select[2]</value>
      <webElementGuid>e11ced5f-55a2-448d-a03a-a3b114701cef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nomor Telepon *'])[1]/preceding::select[1]</value>
      <webElementGuid>c53a0d43-662b-47c4-ada9-5d95a344bcf7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pendidikan Terakhir'])[1]/preceding::select[1]</value>
      <webElementGuid>7312c541-39d3-486f-9d72-2a705620db09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/div[3]/select</value>
      <webElementGuid>f6b0db77-6293-45ec-b40b-adbea713efbc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'Desa' and @name = 'Desa_Kelurahan' and (text() = 'Desa / KelurahanBIKANGGADUNGJERIJIKAPOSANGKEPOHRIASRINDIKSERDANGTANJUNG KETAPANGTELADANTOBOALI' or . = 'Desa / KelurahanBIKANGGADUNGJERIJIKAPOSANGKEPOHRIASRINDIKSERDANGTANJUNG KETAPANGTELADANTOBOALI')]</value>
      <webElementGuid>1bbb640b-6bc6-4083-9242-df63d8eeacec</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
